CREATE DATABASE IF NOT EXISTS livraria_db;
USE livraria_db;

CREATE TABLE IF NOT EXISTS books (
    ID SERIAL PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Author VARCHAR(50) NOT NULL,
    Language VARCHAR(20),
    ISBN VARCHAR(17) NOT NULL,
    Pages INT NOT NULL,
    Price DOUBLE PRECISION NOT NULL);

CREATE TABLE IF NOT EXISTS client(
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  CPF VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Credit 0,
  Cart INTEGER[1000]
);

CREATE TABLE IF NOT EXISTS cashier(
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  CPF VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Manager VARCHAR(50) NOT NULL,
  Salary DOUBLE PRECISION NOT NULL,
  SHIFT VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS manager(  
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  CPF VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Sector CHAR(1) NOT NULL,
  Salary DOUBLE PRECISION NOT NULL);

CREATE TABLE IF NOT EXISTS sales(
ID SERIAL PRIMARY KEY,
Sale_Date TIMESTAMP DEFAULT NOW()

);

CREATE TABLE IF NOT EXISTS order(
  ID INT REFERENCES sales(ID),
  BOOK INT REFERENCES books(ID),
  Qnt INT DEFAULT 1
);